# Generated by Django 5.0.2 on 2024-02-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_dados_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpi',
            name='numero_pi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='multlogpi',
            name='numero_pi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pi',
            name='numero_pi',
            field=models.FloatField(default=0),
        ),
    ]
